#!/bin/sh

IMAGE=image.ext3
LABEL=file-extattr

dd if=/dev/zero of=$IMAGE bs=1024 count=102400
/sbin/mkfs.ext3 -L $LABEL $IMAGE

cat <<EOT
Now mount $IMAGE like so:

mkdir -p /tmp/foo
su -
mount -o loop,nouser_xattr -t ext3 $IMAGE /tmp/foo
EOT
